[calendar]
today = "today"
title = "Assembly Language"
description = """汇编语言（assembly language）是一种用于电子计算机、微处理器、微控制器，或其他可
编程器件的低级语言，最早于 1949 年出现，在不同的设备中，汇编语言对应着不同的机器
言指令集。一种汇编语言专用于某种计算机系统结构，而不像许多高级语言可以在不同的系
统平台自己移植。"""
code = """call get_date \\ lea dx, date
mov ah, 09h \\ int 21h \\ mov ax, 4c00h
int 21h
date:
db "0000-00-00", 0ah, 0dh, '$'
get_date:
mov al, 04h \\ int 1ah \\ mov bx, offset date
mov al, dl \\ call put_bcd2 \\ inc bx
mov al, dh \\ call put_bcd2 \\ inc bx
mov al, ch \\ call put_bcd2 \\ mov al, cl
call put_bcd2 \\ ret
put_bcd2:
push ax \\ shr ax, 4 ] and ax, 0fh
add ax, '0' \\ mov [bx], al \\ inc bx
pop ax, \\ and ax, 0fh \\ add ax, '0'
mov [bx], al \\ inc bx \\ ret
"""
language = "nasm"
output = "output/asm.png"

# 标题
[title]
font = "SpaceMono-Bold.ttf"
font_size = 120
color = [35, 31, 32]
pos = [150, 300]

# 右上方日期
[date]
font = "SpaceMono-Regular.ttf"
font_size = 80
color = [35, 31, 32]
pos = [1250, 500]

# 右上方星期缩写
[today]
font = "SpaceMono-Regular.ttf"
font_size = 60
spacing = 20
pos = [1500, 625]
weekday_color = [35, 31, 32]
weekend_color = [218, 40, 34]

# 右上方中文日期
[date_cn]
font = "NotoSansSC-Regular.otf"
font_size = 50
pos = [1640, 635]
weekday_color = [35, 31, 32]
weekend_color = [218, 40, 34]

# 代码块
[code]
font_size = 40
line_pad = 15
pos = [250, 750]

# 介绍语
[description]
font = "NotoSansSC-Regular.otf"
font_size = 40
spacing = 20
pos = [150, 1800]
color = [107, 105, 106]

# 周历表格
[table]
pos = [[150, 2140], [1725, 2470]]
color = [107, 106, 106]
border = 5
gap = 5
weekday_color = [35, 31, 32]
weekend_color = [218, 40, 34]
    [table.today]
    font = "SpaceMono-Bold.ttf"
    font_size = 70
    [table.date]
    font = "SpaceMono-Regular.ttf"
    font_size = 35
    [table.date_cn]
    font = "NotoSansSC-Regular.otf"
    font_size = 40

[wallpaper]
input = "images/wallpaper.png"
zoom = 0.5
pos = [350, 200]
output = "output/wallpaper_asm.png"
