[calendar]
today = "today"
title = "Lisp"
description = """Lisp 起源于 1958 年，由 John McCarthy 在麻省理工学院发明。它具有独特和完全的括号
前缀符号表示法，是至今第二悠久而仍广泛使用的高级编程语言。因为是早期的高级编程
语言之一，它很快成为当时人工智能研究中最受欢迎的编程语言。"""
code = """(multiple-value-bind
    (second minute hour date month year day-of-week dst-p tz)
    (get-decoded-time)
    (format t \"~d-~2,'0d-~2','0d\"
        year
        month
        date))
"""
language = "lisp"
output = "lisp.png"

# 标题
[title]
font = "SpaceMono-Bold.ttf"
font_size = 120
color = [35, 31, 32]
pos = [150, 300]

# 右上方日期
[date]
font = "SpaceMono-Regular.ttf"
font_size = 80
color = [35, 31, 32]
pos = [1250, 500]

# 右上方星期缩写
[today]
font = "SpaceMono-Regular.ttf"
font_size = 60
pos = [1500, 625]
weekday_color = [35, 31, 32]
weekend_color = [218, 40, 34]

# 右上方中文日期
[date_cn]
font = "NotoSansSC-Regular.otf"
font_size = 50
pos = [1640, 635]
weekday_color = [35, 31, 32]
weekend_color = [218, 40, 34]

# 代码块
[code]
font_size = 40
pos = [250, 750]

# 介绍语
[description]
font = "NotoSansSC-Regular.otf"
font_size = 40
pos = [150, 1800]
color = [107, 105, 106]

# 周历表格
[table]
pos = [[150, 2140], [1725, 2470]]
color = [107, 106, 106]
border = 5
gap = 5
weekday_color = [35, 31, 32]
weekend_color = [218, 40, 34]
    [table.today]
    font = "SpaceMono-Bold.ttf"
    font_size = 70
    [table.date]
    font = "SpaceMono-Regular.ttf"
    font_size = 35
    [table.date_cn]
    font = "NotoSansSC-Regular.otf"
    font_size = 40

[wallpaper]
input = "images/wallpaper.png"
code_zoom = 0.5
code_pos = [350, 200]
output = "wallpaper_lisp.png"